---
title: "Datarobot Task"
output: word_document
---

```{r setoptions, echo=FALSE, results='hide',warning=FALSE}
```

## Include the libraries
```{r setoptions, warning=FALSE}
library(caret)
library(class)
library(e1071)
```
## Loading and preprocessing the data
Read in the data.
```{r}
data1<-read.table("D:/bank.csv",sep=";",header=TRUE)
train <-  data1[1:3000,]
test <-data1[3001:4521,]
test_class <- test$y
test$y <-NULL
```
## Create logistic regression model
```{r}
pred <-glm(y~age+balance+duration+campaign+pdays+previous,data=train,family=binomial(link="logit"))
confint(pred)
```
## Apply the model to the test dataset
```{r}
outc<- predict(pred,test,type = "response")
pred_class <- rep("no",1521)
pred_class[outc > 0.47] = "yes"
```
## Create confusion matix
```{r}
confusionMatrix(pred_class,test_class)
```
## Observations
The logistic prediction model created has an accuracy of 0.886 and high true positive and low false negative rates.This can be inferred from the confusion matrix created.